sudo: required
language: cpp
before_script:
- sudo ./gtest_install_script.sh
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- pwd
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umakerslet:$BINTRAY_API_KEY "https://api.bintray.com/content/makerslet/ipfilter/package/$TRAVIS_BUILD_NUMBER/ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
